version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    working_directory: ~/github.com/doc-digit/api
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t doc-digit/api:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push doc-digit/api:$TAG
