version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/buildpack-deps:18.04
    working_directory: ~/github.com/doc-digit/api
    steps:
      - checkout
      - run:
          name: Run containers using Docker Compose
          command: docker-compose up -d --build
  deploy:
    docker:
      - image: circleci/buildpack-deps:18.04
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - add_ssh_keys:
          fingerprints:
            - "55:69:fa:80:9b:8c:eb:31:de:43:0e:1c:c9:38:8a:0f"
      - run:
          name: Build and push Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t docdigit/api:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push docdigit/api:$TAG
      - run:
          name: Deploy app to Google Compute Engine via Docker
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            ssh -o StrictHostKeyChecking=no koczanm@35.198.90.139 /bin/sh deploy-api.sh docdigit/api:$TAG

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
